### ISSUE TITLE
This doesn't seem to work

### ISSUE THREAD

**Issue by kennym** [solepixel/wp-multiple-passwords#1]
Have you tried this on Wordpress 4.6? I'm very interested in getting this to work on 4.6

**Comment by solepixel** [comment]
I have tested this on WordPress 4.6 with ACF Version 5.3.9. Are you sure Advanced Custom Fields is installed and activated?

If you're still having issues, can you please tell me what is not working? Are you not seeing the "Extra Passwords" meta box? Are the extra passwords not working? Are you using a custom solution? Please elaborate more on what your issue is. Thanks!

**Comment by kennym** [comment]
sorry - I figured it was an issue with a plugin I've installed - OptimizePress. For some reason your plugin won't work with their plugin - I'll report this upstream.

Your plugin works fine. Thanks

**Comment by kennym** [comment]
I won't see the "Extra Passwords" metabox, nor is the filter solution working when I have OptimizePress installed.

**Comment by solepixel** [comment]
The plugin includes support for Pages and Posts. If you're needing support for additional post types, I can add a filter to allow usage on other post types. Curious why the metabox isn't showing up, does OptimizePress have issues working with Advanced custom fields? Otherwise, the filter method should work fine. Keep in mind you need to set the post/page to Password Protected and set an initial password first (and update/save) before the metabox will show up.
