### ISSUE TITLE
Additional Password box is not showing

### ISSUE THREAD

**Issue by TheFoxGraphics** [solepixel/wp-multiple-passwords#6]
Hello,

I have upgraded ACF to 5.x and when I refreshed everything, the Additional Box is not appearing. Instead, I am seeing "Extra Passwords" but with no options to add the additional passwords.

<img width="293" alt="screen shot 2017-12-19 at 10 10 59 am" src="https://user-images.githubusercontent.com/34687058/34166625-fcc21356-e4a4-11e7-93c6-6a8c4eac16d1.png">

I am running WordPress 4.9.1.

Any help to fix this would be greatly appreciated.

Thanks,
Brandon.

**Comment by TheFoxGraphics** [comment]
Any help with this would be greatly appreciated. I am on a tight deadline.

Thanks!
Brandon.

**Comment by solepixel** [comment]
Hey, sorry, holidays got me crazy busy. I'll take a look at this in the morning.

**Comment by TheFoxGraphics** [comment]
That is totally fine! I appreciate it!

Thank you.

Brandon.

**Comment by solepixel** [comment]
@brottmayer Digging into this, tested this on a site I have the latest WP and ACF 5.x installed, showing the additional password button and fields just fine:
http://3cd.co/0D0m0s3m3c3D / http://3cd.co/1Z2P2u3D3a2s

If you'd like me to look into it further, I need to know what plugins you're using and exact version of ACF.

**Comment by TheFoxGraphics** [comment]
I have the latest version of Wordpress installed and updated the ACF to 5.x, but it still doesn't show up for me. Here are the plugins I currently have installed:
 
Advanced Custom Fields
BM Custom Login
Duplicate Page
Font I Want
Intergeo - Google Maps Plugin - Lite
Ninja Forms
Service Box
Smart Passworded Pages
WP Multiple Passwords

Thanks,
Brandon.

**Comment by solepixel** [comment]
I'm using ACF Version 5.6.7. Which version of ACF do you have installed? Also, which version of WP Multiple Passwords are you using? The latest release is 1.1.0. Let me know, thanks!

**Comment by TheFoxGraphics** [comment]
ACF Version 5.6.7
WP Multiple Password Version 1.1.0

**Comment by solepixel** [comment]
This seems to be the same setup I'm using. I would try this first:

1. Deactivate all plugins except ACF & WP Multiple Passwords. If that does not resolve your issue,
2. Switch your theme to TwentySeventeen or one of the Default WordPress themes.
3. Lastly, open your Developer Tools and review the console for Javascript errors. ACF highly relies on Javascript to handle displaying fields so if there's an error caused by another script, it could be breaking the Multiple Passwords functionality.

If your issue is still not resolved, it may require some additional digging to find the issue. I'd be happy to help, but it would fall into custom support which would be charged by the hour. Sorry I couldn't help more. Let me know if you're able to figure it out!

**Comment by TheFoxGraphics** [comment]
OK, thanks for your help.
